// <auto-generated />
using System;
using DiabetesManager.DataAccess;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace DiabetesWebApp.Migrations
{
    [DbContext(typeof(DataContext))]
    partial class DataContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("DiabetesManager.Models.logEntry", b =>
                {
                    b.Property<int>("entryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("entryId"), 1L, 1);

                    b.Property<DateTime>("dateTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("entryBg")
                        .HasColumnType("int");

                    b.Property<int>("entryCarb")
                        .HasColumnType("int");

                    b.Property<double>("entryInsulin")
                        .HasColumnType("float");

                    b.Property<string>("entryNote")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("entryId");

                    b.ToTable("logEntries");
                });

            modelBuilder.Entity("DiabetesManager.Models.userSetting", b =>
                {
                    b.Property<int>("settingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("settingId"), 1L, 1);

                    b.Property<int>("carbRatio")
                        .HasColumnType("int");

                    b.Property<int>("insulinActionTime")
                        .HasColumnType("int");

                    b.Property<int>("insulinCorrectionFactor")
                        .HasColumnType("int");

                    b.Property<int>("lowBglAlert")
                        .HasColumnType("int");

                    b.Property<int>("targetBgl")
                        .HasColumnType("int");

                    b.HasKey("settingId");

                    b.ToTable("userSettings");
                });
#pragma warning restore 612, 618
        }
    }
}
